import { LineEdit } from "std-widgets.slint";

// widget to show not valid data
export component ValidatedInput {
    callback accepted(text: string);
    in-out property <string> text-text <=> input.text;
    in property <string> placeholder-text;
    in-out property <length> height-text;
    in-out property <TextHorizontalAlignment> horizontal-alignment;

    in-out property <bool> has-error: false;


    Rectangle {
        border-width: 1pt;

        border-color: root.has-error ? #ff0000 : transparent;
        border-radius: 4pt;
        animate border-color { duration: 200ms; }

        input := LineEdit {
            accepted(text) => {accepted(text);}
            width: 100%;
            height: height-text;
            placeholder-text: root.placeholder-text;
            horizontal-alignment: horizontal-alignment;
        }
    }
}
