import { Button, VerticalBox, LineEdit } from "std-widgets.slint";
import { ValidatedInput } from "./widgets/validated_input.slint";

export component AppWindow inherits Window {

    property <length> height_: 195pt;
    property <length> width_: 210pt;

    in-out property <bool> first-start: true;
    in-out property <int> active-page: 0;

    in-out property <string> user-name: "";
    in-out property <string> ip: "";
    in-out property <string> port: "";

    in-out property <string> error_reason;

    title: "SimpleChat";

    // making it appear in the same way as linux (debian), since width and height seems to be not enough.
    preferred-height: height_;
    preferred-width: width_;
    max-width: width_;
    max-height: height_;
    min-width: width_;
    min-height: height_;

    // making it appear at the center of the screen, so the first frame is not being rendered somewhere else.
    no-frame: root.first-start;
    //

    x: (root.width - self.width) / 2;
            y: (root.height - self.height) / 2;




    // First Layout
    VerticalLayout {

        opacity: root.first-start ? 0 : 1;
        animate opacity { duration: 1500ms; easing: ease-in-out; delay: 250ms;}
        //


        // page change animation
        x: root.active-page == 0 ? 0pt : -root.width;
        animate x { duration: 250ms; easing: ease-in-out; }
        //

        alignment: center;
        spacing: 20pt;

        // Title layout
        VerticalLayout {
            spacing: 5pt;
            Text {
                text: "Welcome Back!";
                font-size: 16pt;
                horizontal-alignment: center;
            }
            Text {
                text: "Let's begin with connection info:";
                font-size: 11pt;
                horizontal-alignment: center;
            }
        }
        //


        // Data layout
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                spacing: 8pt;
                width: 140pt;

                ValidatedInput {
                    placeholder-text: "IP Address";
                    height-text: 22pt;
                }
                ValidatedInput {
                    placeholder-text: "Port";
                    height-text: 22pt;
                }
                Button {
                    text: "Continue";
                    primary: true;
                    height: 24pt;
                    clicked => { root.active-page = 1; }
                }
            }
        }
        //
    }



    // Second Layout. First index
    VerticalLayout {
        x: root.active-page == 1 ? 0pt : root.width;
        animate x { duration: 250ms; easing: ease-in-out; }

        alignment: center;
        spacing: 20pt;

        // Title layout
        VerticalLayout {
            spacing: 5pt;
            Text {
                text: "Let people know your name";
                font-size: 15.8pt;
                horizontal-alignment: center;
            }
        }

        // Data layout
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                spacing: 8pt;
                width: 140pt;

                ValidatedInput {
                    placeholder-text: "Username";
                    height-text: 22pt;
                    horizontal-alignment: center;
                    accepted(text) => {
                    }
                }

                HorizontalLayout {
                    spacing: 3pt;
                    Button {
                        width: 50%;
                        text: "Return";
                        height: 24pt;
                        clicked => { root.active-page = 2; }
                    }
                    Button {
                        width: 50%;
                        text: "Continue";
                        primary: true;
                        height: 24pt;
                        clicked => { root.active-page = 2; }
                    }

                }
            }
        }
    }


    // Third Layout.
    VerticalLayout {
        // page chnage animation
        y: root.active-page == 2 ? 0pt : root.height;
        animate y { duration: 250ms; easing: ease-in-out; }

        alignment: center;
        spacing: 20pt;

        // Title layout
        VerticalLayout {
            spacing: 5pt;
            Text {
                text: "Final step";
                font-size: 16pt;
                horizontal-alignment: center;
            }
            Text {
                text: "Let's choose the role";
                font-size: 11pt;
                horizontal-alignment: center;
            }
        }

        // Data layout
        HorizontalLayout {
            alignment: center;
            HorizontalLayout {
                spacing: 8pt;
                width: 140pt;

                Button {
                    text: "Server";
                    height: 24pt;
                    clicked => {}
                }
                Button {
                    text: "Client";
                    height: 24pt;
                    clicked => { }
                }
            }
        }
    }

}
